/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Grid: typeof import('./src/components/author/Grid.vue')['default']
    IconBehance: typeof import('./src/components/icons/IconBehance.vue')['default']
    IconBoosty: typeof import('./src/components/icons/IconBoosty.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconDribbble: typeof import('./src/components/icons/IconDribbble.vue')['default']
    IconDzen: typeof import('./src/components/icons/IconDzen.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconGoga: typeof import('./src/components/icons/IconGoga.vue')['default']
    IconInstagram: typeof import('./src/components/icons/IconInstagram.vue')['default']
    IconLink: typeof import('./src/components/icons/IconLink.vue')['default']
    IconPinterest: typeof import('./src/components/icons/IconPinterest.vue')['default']
    IconPlay: typeof import('./src/components/icons/IconPlay.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconRemove: typeof import('./src/components/icons/IconRemove.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTelegram: typeof import('./src/components/icons/IconTelegram.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconVcRu: typeof import('./src/components/icons/IconVcRu.vue')['default']
    IconVK: typeof import('./src/components/icons/IconVK.vue')['default']
    IconYoutube: typeof import('./src/components/icons/IconYoutube.vue')['default']
    LoaderBlock: typeof import('./src/components/loaders/LoaderBlock.vue')['default']
    LoaderTfolio: typeof import('./src/components/loaders/LoaderTfolio.vue')['default']
    LocaleSwitcher: typeof import('./src/components/main/LocaleSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFiles: typeof import('./src/components/author/UploadFiles.vue')['default']
    UploadPopover: typeof import('./src/components/main/UploadPopover.vue')['default']
    UserHeader: typeof import('./src/components/author/UserHeader.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanShareSheet: typeof import('vant/es')['ShareSheet']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
